name: Deploy NEWM Marketplace app to AWS on published release
on:
 release:
   types: [ published ]
 workflow_dispatch:
jobs:
  build_and_deploy_marketplace_release:
    if: ${{ startsWith(github.event.release.tag_name, 'marketplace') }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write # required to interact with GitHub's OIDC Token endpoint.
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Lambda-ify
        run: echo "COPY --from=public.ecr.aws/awsguru/aws-lambda-adapter:0.7.1 /lambda-adapter /opt/extensions/lambda-adapter" >> apps/marketplace/Dockerfile

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_DEPLOY_ROLE_ARN_STUDIO }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy marketplace
        run: |
          npm install --prefix .github/workflows/cdk
          APPNAME=marketplace APPID=Marketplace QUALIFIER=Studio NEXT_PUBLIC_ENV=production NEXT_PUBLIC_RECAPTCHA_SITE_KEY_PROD=${{ secrets.RECAPTCHA_SITE_KEY_PROD }} NEXT_PUBLIC_DEXHUNTER_MARKETPLACE_PARTNER_CODE=${{ secrets.DEXHUNTER_MARKETPLACE_PARTNER_CODE }} npm run --prefix .github/workflows/cdk cdk:deploy deploy -- --require-approval never

      - name: Send update to slack
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "text": "NEWM Marketplace updated in production. View at https://newm.marketplace . View release notes at https://github.com/projectNEWM/newm-web/releases/tag/${{ github.event.release.tag_name }} ."
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_NEWM_MARKETPLACE_WEBHOOK }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
