name: Deploy NEWM Studio to AWS Hosting on PR
on:
  pull_request:
    paths:
      - .github/workflows/aws-hosting-pull-request-newm-studio.yml
      - apps/studio/**
      - packages/**
jobs:
  build_and_preview:
    if: "${{ github.event.pull_request.head.repo.full_name == github.repository }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npx nx build studio
        env:
          VITE_APPLE_CLIENT_ID: ${{ secrets.APPLE_CLIENT_ID }}
          VITE_GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          VITE_GA_STUDIO_ID: ${{ secrets.GA_STUDIO_ID }}
          VITE_RECAPTCHA_SITE_KEY_STAGING: ${{ secrets.RECAPTCHA_SITE_KEY_STAGING }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          VITE_ENV: staging
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_DEPLOY_ROLE_ARN_GARAGE }}
          aws-region: us-west-2
