name: Deploy NEWM Studio to Firebase Hosting on merge
"on":
  push:
    branches:
      - master
    paths:
      - apps/studio/**
      - packages/**
      - Makefile
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npx nx build-with-sentry studio
        env:
          VITE_FACEBOOK_CLIENT_ID: ${{ secrets.FACEBOOK_CLIENT_ID }}
          VITE_GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          VITE_LINKEDIN_CLIENT_ID: ${{ secrets.LINKEDIN_CLIENT_ID }}
          VITE_ENV: ${{ secrets.REACT_APP_ENV }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

      - uses: FirebaseExtended/action-hosting-deploy@v0
        id: deploy
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_NEWM_ARTIST_PORTAL }}"
          channelId: live
          projectId: "${{ secrets.FIREBASE_PROJECT_ID }}"

      - name: Send update to slack
        id: slack
        uses: slackapi/slack-github-action@v1.17.0
        with:
          payload: |
            {
              "text": "Artist Portal updated. View at https://artist.garage.newm.io"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
